[tool.poetry]
name = "eel_ros1"
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
typing-extensions = "^4.12.2"
eel = {extras = ["jinja2"], version = "^0.18.0"}
pyyaml = "^6.0.2"
roslibpy = "^1.8.0"

[tool.poetry.group.dev.dependencies]
taskipy = "^1.14.0"